services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env.prod
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env.prod
    depends_on:
      - db
    networks:
      - app_net

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
