name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /var/www/jacobhyde.com
            
            # Create production env file
            cat > .env.prod << EOF
            # Database Configuration
            MYSQL_ROOT_PASSWORD='${{ secrets.MYSQL_ROOT_PASSWORD }}'
            MYSQL_DATABASE='jacobhyde_db'
            MYSQL_USER='jacobhyde_user'
            MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}'

            # Flask Configuration
            FLASK_ENV=production
            SECRET_KEY='${{ secrets.SECRET_KEY }}'
            JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'

            # Frontend Configuration
            NODE_ENV=production
            REACT_APP_API_URL='https://jacobhyde.com/api'
            EOF
            
            # Set proper permissions
            chmod 600 .env.prod
            
            # Pull latest changes and restart
            git pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            
            # Wait for containers to start and check status
            sleep 10
            docker compose -f docker-compose.prod.yml ps
