name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /var/www/jacobhyde.com
            
            echo "Checking .env.prod file..."
            if [ ! -f .env.prod ]; then
              echo "Error: .env.prod file not found!"
              exit 1
            fi
            
            echo "Verifying environment variables (without showing secrets)..."
            grep -v "PASSWORD\|KEY" .env.prod
            
            echo "Stopping containers..."
            docker compose -f docker-compose.prod.yml down
            
            echo "Starting containers with environment file..."
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d
            
            # Wait for containers to initialize
            echo "Waiting for containers to initialize..."
            sleep 15
            
            echo "Checking MySQL logs..."
            docker compose -f docker-compose.prod.yml logs db
            
            echo "Checking container status..."
            docker compose -f docker-compose.prod.yml ps
